# shellcheck shell=bash
# .envrc / .env の生成。関数定義のみ。
WT_ENVRC_MARKER="# generated by wt"

wt_write_envrc() {
  local dir=$1 repo=$2 wtname=$3 project=$4 host=$5; shift 5
  {
    echo "$WT_ENVRC_MARKER"
    echo "# 編集せず wt setup を再実行すること"
    echo "export DEVENV_REPO=\"$repo\""
    echo "export DEVENV_WORKTREE=\"$wtname\""
    echo "export COMPOSE_PROJECT_NAME=\"$project\""
    echo "export APP_HOST=\"$host\""
    echo "export APP_URL=\"https://$host\""
    local kv
    for kv in "$@"; do echo "export ${kv%%=*}=\"${kv#*=}\""; done
  } > "$dir/.envrc"
}

# ${VAR} と $VAR を現在の環境変数で展開する。未定義は空文字。
wt_expand() {
  python3 -c 'import os, sys; print(os.path.expandvars(sys.argv[1]))' "$1"
}

wt_write_env() {
  local template=$1 out=$2 overrides=$3 key val
  need jq
  cp "$template" "$out"
  while IFS= read -r key; do
    val=$(wt_expand "$(jq -r --arg k "$key" '.[$k]' <<<"$overrides")")
    if grep -qE "^#?[[:space:]]*${key}=" "$out"; then
      awk -v k="$key" -v v="$val" '
        $0 ~ "^#?[[:space:]]*" k "=" { if (!done) { print k "=\"" v "\""; done = 1 }; next }
        { print }' "$out" > "$out.tmp" && mv "$out.tmp" "$out"
    else
      printf '%s="%s"\n' "$key" "$val" >> "$out"
    fi
  done < <(jq -r 'keys[]' <<<"$overrides")
}
