# shellcheck shell=bash
# .envrc / .env の生成。関数定義のみ。
WT_ENVRC_MARKER="# generated by wt"

# ダブルクォート内に置ける形にする: \ と " をエスケープ
wt_dq_escape() { local s=$1; s=${s//\\/\\\\}; s=${s//\"/\\\"}; printf '%s' "$s"; }

wt_write_envrc() {
  local dir=$1 repo=$2 wtname=$3 project=$4 host=$5; shift 5
  {
    echo "$WT_ENVRC_MARKER"
    echo "# 編集しないこと。wt setup で再生成される（setup ステップも再実行される点に注意）"
    echo "export DEVENV_REPO=\"$(wt_dq_escape "$repo")\""
    echo "export DEVENV_WORKTREE=\"$(wt_dq_escape "$wtname")\""
    echo "export COMPOSE_PROJECT_NAME=\"$(wt_dq_escape "$project")\""
    echo "export APP_HOST=\"$(wt_dq_escape "$host")\""
    echo "export APP_URL=\"https://$(wt_dq_escape "$host")\""
    local kv
    for kv in "$@"; do echo "export ${kv%%=*}=\"$(wt_dq_escape "${kv#*=}")\""; done
  } > "$dir/.envrc"
}

# ${VAR} と $VAR を現在の環境変数で展開する。未定義の変数は ${VAR} のまま残す（設定ミスを隠さないため）。
wt_expand() {
  need python3
  python3 -c 'import os, sys; print(os.path.expandvars(sys.argv[1]))' "$1"
}

wt_write_env() {
  local template=$1 out=$2 overrides=$3 key val
  # wt_expand は $(...) の中で呼ばれ、その中の die は伝播しない。ここでも確認する。
  need jq; need python3
  if [ "$template" -ef "$out" ]; then
    die ".env のテンプレートと出力先が同じです: $out"
  fi
  # 1 行目はマーカー。wt 生成物かどうかを cmd_setup が判定できるようにする。
  { echo "$WT_ENVRC_MARKER"; cat "$template"; } > "$out"
  while IFS= read -r key; do
    val=$(wt_expand "$(jq -r --arg k "$key" '.[$k]' <<<"$overrides")")
    if grep -qE "^#?[[:space:]]*${key}=" "$out"; then
      k="$key" ve="$(wt_dq_escape "$val")" awk '
        $0 ~ "^#?[[:space:]]*" ENVIRON["k"] "=" { if (!done) { print ENVIRON["k"] "=\"" ENVIRON["ve"] "\""; done = 1 }; next }
        { print }' "$out" > "$out.tmp" && mv "$out.tmp" "$out"
    else
      printf '%s="%s"\n' "$key" "$(wt_dq_escape "$val")" >> "$out"
    fi
  done < <(jq -r 'keys[]' <<<"$overrides")
}
